### ISSUE TITLE
Collaboration Not Working: `TypeError: can't access property "presenceChannel", this.connector is undefined`

### ISSUE THREAD

**Issue by eiiot** [statamic/collaboration#102]
### Bug description

I just installed collaboration for the first time and it's fully just not functioning. I've tried uninstalling and reinstalling, switching from `reverb` to `pusher` etc. I also get the following error in the browser console:

```
TypeError: can't access property "presenceChannel", this.connector is undefined
    value https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:14
    M https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:21
    initializeEcho https://crimson.test/vendor/collaboration/build/assets/collaboration-df9994a0.js:1
    start https://crimson.test/vendor/collaboration/build/assets/collaboration-df9994a0.js:1
    boot https://crimson.test/vendor/collaboration/build/assets/collaboration-df9994a0.js:1
    boot https://crimson.test/vendor/collaboration/build/assets/collaboration-df9994a0.js:1
    <anonymous> https://crimson.test/vendor/collaboration/build/assets/collaboration-df9994a0.js:1
    start https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:21
    start https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:21
    mounted https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:641
    invokeWithErrorHandling https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:5
    callHook$1 https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:5
    mountComponent https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:5
    $mount https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:5
    $mount https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:9
    _init https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:5
    Vue$3 https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:5
    start https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js:171
    <anonymous> data:text/javascript;base64,U3RhdGFtaWMuY29uZmlnKFN0YXRhbWljQ29uZmlnKTsgU3RhdGFtaWMuc3RhcnQoKQ==:1
[app-4fb7000f.js:5:38036](https://crimson.test/vendor/statamic/cp/build/assets/app-4fb7000f.js)
```

This installation is using eloquent-driver to manage entries, I guess it could be an issue with that? 

### How to reproduce

1. Install the collaboration plugin
2. Check the browser console?

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.7.0
PHP Version: 8.3.6
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: crimson.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 PRO

Statamic Addons
statamic/collaboration: 1.0.0
statamic/eloquent-driver: 4.12.2

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```
